### ISSUE TITLE
Cursor Style

### ISSUE THREAD

**Issue by karma-riuk** [styluslabs/stylusboard#2]
Good afternoon,

I've recently discovered your beautiful app and I find really nice so far.

There is one thing that is bugging me though... I don't understand how to change the style of the cursor and it's bothering me a bit. Every time I lift up my pen, the cursor appears and disapears as soon as I start writing again. The thing that is bothering me here is not the cursor in itself, but its style.
I write with a very thin pen, and seeing a big white circle appearing and dispearing constantly while I'm writing is a bit distracting. [This](https://i.imgur.com/QZjbI3z.gifv) is what it looks like.

I saw that in the `Advanced Settings -> User Interface` there is the option `Cursor Mode`, which we may select from 3 items. The last of these items is `Custom` and that made me think that there was maybe a way to customize the cursor, but I haven't found that way.
I tried tweaking the config file a bit, with no success.

I was using MyPaint before switching to your application and I really liked the feel of that cursor, it was much less distracting. [This](https://i.imgur.com/KWN1Xj7.gifv) is what it looked like on MyPaint.
Do you know how I could get this type of cursor?

For your information (even though it might not be very useful), I'm on Ubuntu 18.04 LTS, with i3wm and the graphical tablet I use to write is a Wacom Bamboo (a pretty old version, like [this one](https://www.amazon.com/Wacom-Bamboo-Capture-Tablet-CTH470/dp/B005HGBEZ2))
Let me know if you need more information to help you solve my problem.

Thanks a lot in advance for your help :)

**Comment by styluslabs** [comment]
Hi,
  This repo is just for the the shared whiteboard server for Write.  For questions about the app itself, it is best to email support@styluslabs.com  Do you find that the cursor is too big on white paper as well, or only on black paper?
