### ISSUE TITLE
What is your program licenced under? GPLv3? Thank you

### ISSUE THREAD

**Issue by ovari** [styluslabs/stylusboard#4]

**Comment by styluslabs** [comment]
You're free to use it however you like.  Stylusboard isn't really useful without the Write app, which isn't open source yet

**Comment by ovari** [comment]
> Stylusboard isn't really useful without the Write app, which isn't open source yet

Do you have an ETA when the Write app will be open-sourced?

It could be very useful in [Jami](https://jami.net/) to enable collaboration _without_ a server.

Please see the Jami issue at https://git.jami.net/savoirfairelinux/jami-project/-/issues/1010#note_33163

Thank you

**Comment by Shahin-rmz** [comment]
may I ask why it is not open source?
